# Generated by Django 5.1 on 2024-08-15 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("autor", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disp", "Disponível"),
                            ("indisp", "Emprestado"),
                            ("devol", "Devolvido"),
                        ],
                        default="disp",
                        max_length=20,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Emprestado para",
                    ),
                ),
            ],
        ),
    ]
