# Generated by Django 5.1 on 2024-08-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0002_alter_livro_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="estante",
            field=models.CharField(
                choices=[
                    ("1", "Estante 1"),
                    ("2", "Estante 2"),
                    ("3", "Estante 3"),
                    ("4", "Estante 4"),
                    ("5", "Estante 5"),
                    ("6", "Estante 6"),
                    ("7", "Estante 7"),
                    ("8", "Estante 8"),
                    ("9", "Estante 9"),
                ],
                default="1",
                max_length=10,
                verbose_name="Estante",
            ),
        ),
    ]
