# Generated by Django 5.1 on 2024-08-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emprestimo", "0002_rename_book_emprestimo_livro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="status",
            field=models.CharField(
                choices=[("emprestado", "Emprestado"), ("devolvido", "Devolvido")],
                default="emprestado",
                max_length=10,
            ),
        ),
    ]
