# Generated by Django 5.1 on 2024-08-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="serie_turma",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("6A", "6A"),
                    ("6B", "6B"),
                    ("6C", "6C"),
                    ("7A", "7A"),
                    ("7B", "7B"),
                    ("7C", "7C"),
                    ("8A", "8A"),
                    ("8B", "8B"),
                    ("8C", "8C"),
                    ("9A", "9A"),
                    ("9B", "9B"),
                    ("9C", "9C"),
                ],
                default="6A",
                max_length=10,
                verbose_name="Série/Turma",
            ),
        ),
    ]
